### ISSUE TITLE
Running on different architectures

### ISSUE THREAD

**Issue by Quba1** [NCAR/pi-wrf#16]
Pi-WRF seems great for some simple presentations of NWP models, but I don't have a Raspberry Pi. So I am wondering, is it possible to run pi-wrf on some different machine than Raspberry Pi? For example, just a computer with Ubuntu?

I've read that there are some options for multiarch builds in Docker, but I'm not very familiar with Docker so I want to check first if there is an easier solution.

**Comment by wefoust** [comment]
Hi,
It is technically possible to run on other architectures, but it will be very difficult to set this up. This is because WRF needs to be compiled for each system. In order for the app to work on another system, WRF, WPS, Python, and NCL will need to be compiled, and then a user will need to link these programs to Pi-WRF. Docker was used as a means of preventing a user from compiling these programs for their system. 

Have you compiled WRF and NCL already? If so, what operating system are you using? If you are interested, I may be able to walk you through this process.
