### ISSUE TITLE
Viewing Output

### ISSUE THREAD

**Issue by jdrudd2** [NCAR/pi-wrf#4]
Hello,

Quite new to all of this, so forgive me...

When I run this app and it generates images, is there a way to step through multiple days/hours of output? It seems I am only getting one image for temps, one image for precip, etc. And, I do not know what date/time it is valid for. Can a timestamp be added?

Thanks for any help!

**Comment by wefoust** [comment]
Thanks for mentioning this. Since this project is still in its infancy, we've only included a very small set of plots in attempt to avoid "overwhelming" novices and new users with an abundance of plots. However, several others have made similar inquiries about more visualization options, and we agree that they will be good additions. We will incorporate the features you have mentioned in a later release.

If you need something more immediate, I can devise a "hot fix" for you. Granted, it may be a messy solution, but it will suffice at least temporarily. 

Again, thank you for you input because it does help drive our development. 
~Eliott

**Comment by wefoust** [comment]
Hi jdrudd2,
A recent update was pushed and the app now allows a user to step through images. I'll mark this issue as closed.
